---
# Deploy a small system for evaluation with CITC
#
- name: wait a bit for the deployment to settle down
  pause:
    seconds: 300

- name: collect networks
  command: openstack {{ openstack.demo_credentials }} network list
  register: _networks

- name: Create demo net
  command: openstack {{ openstack.demo_credentials }} network create demonet
  when: "'demonet' not in _networks.stdout"

- name: Define demonet subnet
  command: openstack {{ openstack.demo_credentials }} subnet create --network demonet --subnet-range 200.0.0.0/24 --dns-nameserver 8.8.8.8 --gateway 200.0.0.1 demonet
  when: "'demonet' not in _networks.stdout"

- name: Create router to get in/out
  command: openstack {{ openstack.demo_credentials }} router create demorouter
  when: "'demonet' not in _networks.stdout"

- name: Connect the router to demonet
  command: openstack {{ openstack.demo_credentials }} router add subnet demorouter demonet
  when: "'demonet' not in _networks.stdout"

- name: Connect the router to the provider network
  command: openstack {{ openstack.demo_credentials }} router set --external-gateway provider demorouter
  when: "'demonet' not in _networks.stdout"

- name: Connect the router to the provider network
  command: openstack {{ openstack.demo_credentials }} server create --flavor m1.nano --image cirros --nic net-id=demonet {{ item }}
  with_items:
  - cirros1
  - cirros2
  when: "'demonet' not in _networks.stdout"

- name: get a floating IP address
  command: openstack {{ openstack.demo_credentials }} floating ip create provider
  when: "'demonet' not in _networks.stdout"
- shell: openstack {{ openstack.demo_credentials }} floating ip list -c "Floating IP Address" -f value
  register: _floating_ip
  when: "'demonet' not in _networks.stdout"

- name: Assign it to the cirros1
  command: "openstack {{ openstack.demo_credentials }} server add floating ip cirros1 {{ _floating_ip.stdout }}"
  when: "'demonet' not in _networks.stdout"

- name: Make sure to re-start the cirros twins when the machines restart... CITC artifact :-)
  blockinfile:
    dest: /etc/rc.local
    insertbefore: "exit 0"
    marker: "# {mark} ANSIBLE MANAGED BLOCK restart openstack servers after reboot"
    block: |
      sleep 120
      . /home/cumulus/demo-openrc
#      openstack server start cirros1
#      openstack server start cirros2
  become: true
  when: "'demonet' not in _networks.stdout"
...
