---
- set_fact:
    myvars: "{{ switchvars[inventory_hostname] }}"

- name:  BGP unnumbered (v4/v6) on agg ports
  nclu:
    commands:
    - add bgp autonomous-system {{ myvars.ASN }}
    - add loopback lo ip address {{ myvars.V4 }}/32
    - add bgp router-id {{ myvars.V4 }}
    - add loopback lo ipv6 address {{ myvars.V6 }}/128
    - add bgp ipv4 unicast network {{ myvars.V4 }}/32
    - add bgp ipv6 unicast network {{ myvars.V6 }}/128
    - add bgp bestpath as-path multipath-relax
    - add bgp neighbor {{ AGG_IFS }} interface remote-as external
    - add bgp ipv4 unicast neighbor {{ AGG_IFS }} activate
    - add bgp ipv6 unicast neighbor {{ AGG_IFS }} activate
    atomic: true
    description: "unnumbered BGP on the agg ports"
...
